# Generated by Django 5.1.3 on 2024-11-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_refillrequest_options_refillrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refillrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Refill Request', 'verbose_name_plural': 'Refill Requests'},
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this refill request'),
        ),
    ]
