# Generated by Django 5.1.3 on 2024-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medication_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
